const data = {
  products:[
      {
       _id:'1',
       name:'Nike Slim Shirt',
       category:'Shirts',
       Image:'/images/p1.jpg',
       price: 120,
       countInStock: 10,
       brand: 'Nike',
       rating: 4.5,
       numReviews: 10,
       description:'high quality product',  
      },
      {
        _id:'2',
        name:'Lacoste Free Shirt',
        category:'Shirts',
        Image:'/images/p3.jpg',
        price: 220,
         countInStock: 20,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description:'high quality product',  
       }, 
       {
        _id:'3',
        name:'Nike Slim Pant',
        category:'Pants',
        Image:'/images/p4.jpg',
        price: 78,
         countInStock: 0,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description:'high quality product',  
       },
        {
        _id:'4',
        name:'Puma Slim Pant',
        category:'Pants',
        Image:'/images/p5.jpg',
        price: 65, 
        countInStock: 15,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description:'high quality product',  
       },
        {
        _id:'5',
        name:'Nike Slim Shirt',
        category:'Shirts',
        Image:'/images/p1.jpg',
        price: 120,
         countInStock: 5,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description:'high quality product',  
       }, 
       {
        _id:'6',
        name:'Adidas Fit Pant',
        category:'Pants',
        Image:'/images/p6.jpg',
        price: 139, 
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description:'high quality product',  
       },
  ],
};
export default data;